"use client";
import { FormEvent, useState } from "react";

type Connection = { id: string; name: string; rfc: string; branch: string; site: string };
type Result = { folioOrden: string; usuario: string; fechaHora: string; fuente: string; producto?: string; descripcion?: string };
const today = new Date().toISOString().slice(0, 10);

export default function ReportClient({ connections }: { connections: Connection[] }) {
  const [loggedIn, setLoggedIn] = useState(false); const [error, setError] = useState(""); const [results, setResults] = useState<Result[]>([]); const [loading, setLoading] = useState(false);
  async function login(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const data = new FormData(event.currentTarget); const response = await fetch("/api/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: data.get("email"), password: data.get("password") }) }); if (response.ok) setLoggedIn(true); else setError((await response.json()).error); }
  async function report(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); const params = new URLSearchParams(new FormData(event.currentTarget) as never); const response = await fetch(`/api/report?${params}`); const data = await response.json(); setLoading(false); if (!response.ok) { setError(data.error); return; } setResults(data.results); }
  if (!loggedIn) return <main className="login"><section><p className="eyebrow">SiNube</p><h1>Reporte de OP</h1><p>Acceso exclusivo para administradores.</p><form onSubmit={login}><label>Correo<input name="email" type="email" required /></label><label>Contraseña<input name="password" type="password" required /></label><button>Ingresar</button>{error && <p className="error">{error}</p>}</form></section></main>;
  return <main><header><div><p className="eyebrow">SiNube · Administrador</p><h1>Usuarios y órdenes de producción</h1></div></header><section className="filters"><form onSubmit={report}><label>Cliente y sucursal<select name="connection" required>{connections.map((item) => <option value={item.id} key={item.id}>{item.name} · {item.branch}</option>)}</select></label><label>Desde<input name="from" type="date" defaultValue={today} required /></label><label>Hasta<input name="to" type="date" defaultValue={today} required /></label><label>Hora inicial<input name="fromHour" type="time" defaultValue="10:00" required /></label><label>Hora final<input name="toHour" type="time" defaultValue="23:00" required /></label><button disabled={loading}>{loading ? "Consultando…" : "Generar reporte"}</button></form>{error && <p className="error">{error}</p>}</section><section className="results"><div className="summary"><h2>Resultados</h2><span>{results.length} registros</span></div>{results.length ? <table><thead><tr><th>Usuario</th><th>Folio OP</th><th>Fecha y hora</th><th>Origen</th><th>Producto</th><th>Descripción</th></tr></thead><tbody>{results.map((row, index) => <tr key={`${row.usuario}-${row.folioOrden}-${index}`}><td>{row.usuario}</td><td>{row.folioOrden}</td><td>{row.fechaHora}</td><td>{row.fuente}</td><td>{row.producto ?? "—"}</td><td>{row.descripcion ?? "—"}</td></tr>)}</tbody></table> : <p className="empty">Selecciona filtros y genera el reporte.</p>}</section></main>;
}

